from dataclasses import dataclass, field, asdict
from typing import Optional, List, Dict
from datetime import datetime
import json
import os


@dataclass
class SubTask:
    """A single sub-task within a task plan."""
    id: str
    description: str
    status: str = "pending"  # pending, in_progress, completed, skipped
    notes: str = ""
    completed_iteration: Optional[int] = None
    completed_at: Optional[str] = None

@dataclass
class TaskPlan:
    """Task plan generated by the LLM for complex tasks."""
    overview: str = ""
    subtasks: List[SubTask] = field(default_factory=list)

    @property
    def current_subtask_id(self) -> Optional[str]:
        """Return the id of the first non-pending subtask, or None."""
        for st in self.subtasks:
            if st.status in ("in_progress", "completed"):
                return st.id
        return None

    @property
    def completed_count(self) -> int:
        return sum(1 for st in self.subtasks if st.status == "completed")

    @property
    def total_count(self) -> int:
        return len(self.subtasks)

    def update_subtask_status(self, subtask_id: str, status: str, notes: str = "", iteration: Optional[int] = None) -> bool:
        """Update a subtask's status. Returns True if found and updated."""
        for st in self.subtasks:
            if st.id == subtask_id:
                old = st.status
                st.status = status
                if notes:
                    st.notes = notes
                if status == "completed" and iteration is not None:
                    st.completed_iteration = iteration
                    st.completed_at = datetime.now().isoformat()
                return old != status
        return False

    def add_subtask(self, description: str, iteration: Optional[int] = None) -> SubTask:
        """Add a new subtask with auto-incremented id. Returns the new SubTask."""
        new_id = str(max((int(st.id) for st in self.subtasks), default=0) + 1)
        st = SubTask(
            id=new_id,
            description=description,
            completed_iteration=iteration
        )
        self.subtasks.append(st)
        return st

    def remove_subtask(self, subtask_id: str) -> bool:
        """Remove a subtask by id. Returns True if found and removed."""
        for i, st in enumerate(self.subtasks):
            if st.id == subtask_id:
                self.subtasks.pop(i)
                return True
        return False

    def modify_subtask(self, subtask_id: str, description: Optional[str] = None, notes: Optional[str] = None) -> bool:
        """Modify a subtask's description or notes. Returns True if found and modified."""
        for st in self.subtasks:
            if st.id == subtask_id:
                if description is not None:
                    st.description = description
                if notes is not None:
                    st.notes = notes
                return True
        return False


@dataclass
class IterationRecord:
    iteration_number: int
    timestamp: str
    image_path: str
    prompt: str
    llm_response: str
    execution_success: bool
    task_status: str
    
    image_base64: Optional[str] = None
    context: Optional[str] = None
    parsed_action: Optional[str] = None
    parsed_element: Optional[str] = None
    parsed_input: Optional[str] = None
    parsed_key: Optional[str] = None
    reasoning: Optional[str] = None
    execution_result: Optional[str] = None
    execution_error: Optional[str] = None
    screen_changed: bool = False
    new_elements_detected: List[str] = field(default_factory=list)
    helpful: bool = False
    confidence: float = 0.0

@dataclass
class ReActMemory:
    session_id: str
    task_description: str
    start_time: str
    end_time: Optional[str] = None

    iterations: List[IterationRecord] = field(default_factory=list)
    successful_actions: Dict[str, List[int]] = field(default_factory=dict)
    failed_actions: Dict[str, List[int]] = field(default_factory=dict)
    key_findings: List[str] = field(default_factory=list)
    strategy_adjustments: List[str] = field(default_factory=list)

    final_status: Optional[str] = None
    final_reasoning: Optional[str] = None

    task_plan: Optional[TaskPlan] = None

class ReActMemoryStore:
    
    def __init__(self, storage_dir: Optional[str] = None):
        self.memories: Dict[str, ReActMemory] = {}
        self.storage_dir = storage_dir
    
    def create_memory(self, session_id: str, task: str) -> ReActMemory:
        memory = ReActMemory(
            session_id=session_id,
            task_description=task,
            start_time=datetime.now().isoformat()
        )
        self.memories[session_id] = memory
        return memory
    
    def add_iteration(self, session_id: str, record: IterationRecord):
        if session_id in self.memories:
            self.memories[session_id].iterations.append(record)
    
    def update_patterns(self, session_id: str, record: IterationRecord):
        memory = self.memories.get(session_id)
        if not memory:
            return
        
        action_key = f"{record.parsed_action}:{record.parsed_element}"
        
        if record.execution_success and record.helpful:
            if action_key not in memory.successful_actions:
                memory.successful_actions[action_key] = []
            memory.successful_actions[action_key].append(record.iteration_number)
        elif not record.execution_success:
            if action_key not in memory.failed_actions:
                memory.failed_actions[action_key] = []
            memory.failed_actions[action_key].append(record.iteration_number)
    
    def finalize_memory(self, session_id: str, final_status: str, final_reasoning: Optional[str] = None):
        memory = self.memories.get(session_id)
        if memory:
            memory.end_time = datetime.now().isoformat()
            memory.final_status = final_status
            memory.final_reasoning = final_reasoning
            
            if self.storage_dir:
                self._save_to_file(memory)
    
    def _save_to_file(self, memory: ReActMemory):
        os.makedirs(self.storage_dir, exist_ok=True)
        filename = f"{memory.session_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        filepath = os.path.join(self.storage_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(asdict(memory), f, ensure_ascii=False, indent=2)

    def set_task_plan(self, session_id: str, plan: TaskPlan):
        """Set or update the task plan for a session."""
        memory = self.memories.get(session_id)
        if memory:
            memory.task_plan = plan

    def update_subtask_status(self, session_id: str, subtask_id: str, status: str, notes: str = "", iteration: Optional[int] = None) -> bool:
        """Update a subtask status within the task plan."""
        memory = self.memories.get(session_id)
        if memory and memory.task_plan:
            return memory.task_plan.update_subtask_status(subtask_id, status, notes=notes, iteration=iteration)
        return False

    def apply_plan_update(self, session_id: str, update: Dict) -> bool:
        """
        Apply a dynamic plan update (add/remove/modify subtask, or update overview).
        update: Dict with 'operation' key and additional fields:
        - operation="add", description="...", insert_after_id="N" (optional)
        - operation="remove", subtask_id="N"
        - operation="modify", subtask_id="N", description="...", notes="..."
        - operation="update_overview", overview="..."
        Returns True if applied successfully.
        """
        memory = self.memories.get(session_id)
        if not memory or not memory.task_plan:
            return False
        plan = memory.task_plan
        op = update.get("operation")
        if op == "add":
            description = update.get("description", "").strip()
            if not description:
                return False
            insert_after = update.get("insert_after_id")
            new_st = plan.add_subtask(description)
            # Move to correct position if insert_after_id specified
            if insert_after:
                for i, st in enumerate(plan.subtasks):
                    if st.id == insert_after:
                        # Move new subtask (last) to position after insert_after
                        plan.subtasks.pop()
                        plan.subtasks.insert(i + 1, new_st)
                        break
            return True
        elif op == "remove":
            return plan.remove_subtask(update.get("subtask_id", ""))
        elif op == "modify":
            sid = update.get("subtask_id", "")
            desc = update.get("description")
            notes = update.get("notes")
            return plan.modify_subtask(sid, description=desc, notes=notes)
        elif op == "update_overview":
            overview = update.get("overview", "").strip()
            if overview:
                plan.overview = overview
                return True
        return False
